package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gates generated by hbm2java
 */

@Entity
@Table(name="Gates")
public class Gates implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name="id")
	private int id;

	@Column(name="Terminal_id")
	private int terminal_id;
	
	@Column(name="name")
	private String name;

	public Gates() {
	}

	public Gates(int id, int terminals) {
		this.id = id;
		this.terminal_id = terminals;
	}

	public Gates(int id, int terminals, String name) {
		this.id = id;
		this.terminal_id = terminals;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public int getTerminal_id() {
		return terminal_id;
	}

	public void setTerminal_id(int terminal_id) {
		this.terminal_id = terminal_id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
