package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlaneMovements generated by hbm2java
 */

@Entity
@Table(name="PlaneMovements")
public class PlaneMovements implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="plane_id")
	private int plane_id;
	
	@Column(name="posx")
	private Double posx;
	
	@Column(name="posy")
	private Double posy;

	public PlaneMovements() {
	}

	public PlaneMovements(int id, int plane_id) {
		this.id = id;
		this.plane_id = plane_id;
	}

	public PlaneMovements(int id, int plane_id, Double posx, Double posy) {
		this.id = id;
		this.plane_id = plane_id;
		this.posx = posx;
		this.posy = posy;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getPlanes() {
		return this.plane_id;
	}

	public void setPlanes(int plane_id) {
		this.plane_id = plane_id;
	}

	public Double getPosx() {
		return this.posx;
	}

	public void setPosx(Double posx) {
		this.posx = posx;
	}

	public Double getPosy() {
		return this.posy;
	}

	public void setPosy(Double posy) {
		this.posy = posy;
	}
}
