package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlaneModels generated by hbm2java
 */

@Entity
@Table(name="PlaneModels")
public class PlaneModels implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="manufacturer_id")
	private int manufacturer_id;
	
	@Column(name="name")
	private String name;
	
	@Column(name="max_passengers")
	private Integer maxPassengers;
	
	public PlaneModels() {
	}

	public PlaneModels(int id) {
		this.id = id;
	}

	public PlaneModels(int id, int manufacturer_id, String name, Integer maxPassengers) {
		this.id = id;
		this.manufacturer_id = manufacturer_id;
		this.name = name;
		this.maxPassengers = maxPassengers;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getManufacturer_id() {
		return manufacturer_id;
	}

	public void setManufacturer_id(int manufacturer_id) {
		this.manufacturer_id = manufacturer_id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getMaxPassengers() {
		return this.maxPassengers;
	}

	public void setMaxPassengers(Integer maxPassengers) {
		this.maxPassengers = maxPassengers;
	}
}
