package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Routes generated by hbm2java
 */

@Entity
@Table(name="Routes")
public class Routes implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="Airline_id")
	private int airline_id;
	
	@Column(name="detination")
	private String detination;
	
	@Column(name="origin")
	private String origin;
	
	@Column(name="departure")
	private String departure;
	
	@Column(name="arrival")
	private String arrival;

	public Routes() {
	}


	public Routes(int id, int airlines, String detination, String origin, String departure, String arrival) {
		this.id = id;
		this.airline_id = airlines;
		this.detination = detination;
		this.origin = origin;
		this.departure = departure;
		this.arrival = arrival;

	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getAirline_id() {
		return airline_id;
	}


	public void setAirline_id(int airline_id) {
		this.airline_id = airline_id;
	}

	public String getDetination() {
		return this.detination;
	}

	public void setDetination(String detination) {
		this.detination = detination;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public String getDeparture() {
		return this.departure;
	}

	public void setDeparture(String departure) {
		this.departure = departure;
	}

	public String getArrival() {
		return this.arrival;
	}

	public void setArrival(String arrival) {
		this.arrival = arrival;
	}
}
