package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tickets generated by hbm2java
 */

@Entity
@Table(name="Tickets")
public class Tickets implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="Flight_id")
	private int flight_id;
	
	@Column(name="Passenger_id")
	private int passenger_id;
	
	@Column(name="code")
	private String code;

	public Tickets() {
	}

	public Tickets(int id, int flights, int passengers, String code) {
		this.id = id;
		this.flight_id = flights;
		this.passenger_id = passengers;
		this.code = code;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getFlight_id() {
		return flight_id;
	}

	public void setFlight_id(int flight_id) {
		this.flight_id = flight_id;
	}

	public int getPassenger_id() {
		return passenger_id;
	}

	public void setPassenger_id(int passenger_id) {
		this.passenger_id = passenger_id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
